name: qGP-Contexts
version: '${project.version}'
main: gg.quartzdev.qgpcontexts.QGPContexts
api-version: '1.16.5'
dependencies:
  server:
    GriefPrevention:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: true
    HuskClaims:
      load: BEFORE
      required: false